# action.yml
name: 'Bugfixer'
description: 'Fix some bugs'
inputs:
  issue_text:  # id of input
    description: 'The body of an issue in the correct format'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
